name: AtomicDex-Desktop VirustTotal Release

on:
  release:
    types: [published]

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2.4.1
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          github_token: ${{ github.token }}
          files: |
            .exe$
            .AppImage$
            .zip$
            .tar.zst$
            .dmg$
            .7z$
